title: Your awesome title
author: MichaelCurrin
email:
description:

# Social links
github_username: MichaelCurrin
rss: rss

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
