### Site metadata ###

title: Minima
author: MichaelCurrin
email:
description:

github_username: MichaelCurrin
rss: RSS

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/minima"

theme: minima
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"

titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - bin/
  - docs/
  - simple-icons/
  - vendor/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
