### Site metadata ###

title: Your awesome title
author: MichaelCurrin
email:
description:

github_username: MichaelCurrin
rss: RSS

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/minima"

theme: minima

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
