### Site metadata ###

title: Fractal
description: A customized Jekyll theme to support my sites about coding

author: Michael Currin
email:
github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/fractal"

theme: fractal

show_excerpts: false

fractal:
  date_format: "%b %-d, %Y"

titles_from_headings:
  strip_title: true

header_pages:
  - index.md
  - demo/index.md
  - logos.md
  - flexbox.md

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - bin/
  - docs/
  - hooks/
  - simple-icons/
  - vendor/
  - Gemfile
  - LICENSE
  - Makefile
  - fractal.gemspec
  - "*.gem"
  - README.md
